aiEngine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dataset/', include('dataset.urls', namespace='dataset')),
    path('model/', include('modelMarketplace.urls', namespace='model')),
    path('', include('project.urls', namespace='project')),
    path('__debug__/', include('debug_toolbar.urls'))
]

dataset/urls.py
from django.urls import path
from dataset import views

app_name = 'dataset'

urlpatterns = [
    path('<int:pk>/create', views.datasetCreate, name='datasetCreate'),
    path('<int:pk>/delete/<str:data_pk>', views.datasetDelete, name='datasetDelete'),
    path('<int:pk>/getData', views.getStorageData, name='s3Data'),
]

project/urls.py
from django.urls import path
from project import views

app_name = 'project'

urlpatterns = [
    # folder
    # path('api', views.projectView),
    # path('api/<int:pk>', views.projectView),
    # path('api/delete/<int:pid>', views.projectDelete),
    # path('api/update/<int:pid>', views.projectUpdate),

    # views
    path('', views.index, name='index'),
    path('projects', views.projectView, name='projects'),
    path('<int:pk>', views.projectDetailedView, name='project'),
    path('create', views.createProject, name='projectCreate'),
    path('update', views.updateProject, name='projectUpdate'),
    path('instance/<int:pk>', views.projectInstance, name='projectInstance'),
    path('delete/<int:pk>', views.deleteProject, name='projectDelete'),
]

project/models.py
from django.db import models


class Project(models.Model):
    STATUS_CHOICES = (
        ('Complete', 'complete'),
        ('Active', 'active'),
        ('Inactive', 'inactive'),
    )

    project_name = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Active', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.project_name

    class Meta:
        verbose_name_plural = 'Project'

project/forms.py
from django import forms
from project.models import Project


class ProjectForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Project
        fields = '__all__'

project/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from project.models import Project
from project.forms import ProjectForm
from dataset.models import Dataset
from dataset.forms import DatasetForm
from modelMarketplace.models import ModelSetup, ModelTrainingConfig, ModelHistoryDetails
from modelMarketplace.forms import ModelSetupForm, ModelTrainingConfigForm, ModelHistoryDetailsForm

def index(request):
    return render(request, 'dashboard/main.html')


def projectView(request):

    form = ProjectForm()
    data = Project.objects.all()
    context = {"projects": data, "form": form}
    return render(request, 'pages/project/project.html', context)


def projectDetailedView(request, pk):
    project = Project.objects.get(id=pk)
    datasets = Dataset.objects.filter(project=project.id)
    models = ModelSetup.objects.all()
    datasetForm = DatasetForm()
    modelSetupForm = ModelSetupForm()
    modelConfigForm = ModelTrainingConfigForm()
    context = {"project": project,
               "datasets": datasets,
               "datasetForm": datasetForm,
               "models": models,
               "modelForm": modelSetupForm,
               "modelConfigForm": modelConfigForm}
    return render(request, 'pages/project/projectDetail.html', context)


def createProject(request):
    form = ProjectForm(request.POST)
    if form.is_valid():
        form.save()
    else:
        messages.warning(request, "Unable to add project")
    data = Project.objects.all()
    context = {"projects": data}
    return render(request, 'pages/project/partials/table.html', context)


def projectInstance(request, pk):
    """
    When update button is clicked, this function receives a GET request to render
    Update form populated with the instance associated with the id
    :param request:
    :param pk:
    :return: Update Form with instance
    """
    instance = Project.objects.get(id=pk)
    form = ProjectForm(instance=instance)
    context = {"form": form}
    return render(request, 'pages/project/partials/updateForm.html', context)


def updateProject(request):
    project_id = request.POST.get('id')
    instance = Project.objects.get(id=project_id)
    form = ProjectForm(request.POST, instance=instance)
    if form.is_valid():
        form.save()
    else:
        messages.danger(request, "Unable to Update Project")
    data = Project.objects.all()
    context = {"projects": data}
    return render(request, 'pages/project/partials/table.html', context)


@csrf_exempt
def deleteProject(request, pk):
    project = Project.objects.get(id=pk)
    project.delete()
    data = Project.objects.all()
    context = {"projects": data}
    return render(request, 'pages/project/partials/table.html', context)



templates/pages/project/project.html
{% extends 'layout/app.html' %}

{% block title %} Project {% endblock %}


{% load static %}
{% load widget_tweaks %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-main">
                    <h4 class="text-capitalize breadcrumb-title">Project</h4>
                    <div class="breadcrumb-action justify-content-center flex-wrap">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#"><i
                                        class="las la-home"></i>Project</a></li>
                                <li class="breadcrumb-item active"
                                    aria-current="page">Projects
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="breadcrumb-main m-0 breadcrumb-main--table justify-content-sm-between ">
                <div class="action-btn">
                    <a href="{% url 'project:projectCreate' %}">
                        <a class="btn btn-primary shadow" data-bs-toggle="modal" href="#addProject" role="button" aria-expanded="false" aria-controls="collapseOne">Add Project</a>
                    </a>
                </div>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12 mb-30">
                <div class="support-ticket-system support-ticket-system--search">
                    <div class="userDatatable userDatatable--ticket userDatatable--ticket--2 mt-1">
                        <div class="table-responsive" id="projectList">
                            {% include 'pages/project/partials/table.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- {# ADD PROJECT MODAL FORM #} -->
    <div class="modal fade" id="addProject" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header justify-content-center">
                    <h5 class="modal-title" id="exampleModalLabel">Add Project</h5>
                </div>
                <div class="modal-body">
                    <form method="POST" id="addForm">
                        {% csrf_token %}
                        <div class="mb3">
                            <label for="a8" class="il-gray fs-14 fw-500 align-center mb-10">Name of Project</label>
                            {% render_field form.project_name class="form-control" %}
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary" hx-post="{% url 'project:projectCreate' %}"
                                    hx-target="#projectList" data-bs-dismiss="modal">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- {# FIRST MODAL END #} -->

    <!-- {# UPDATE PROJECT MODAL FORM #} -->
    <div class="modal fade" id="updateProject" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header justify-content-center">
                    <h5 class="modal-title" id="exampleModalLabel">Update Project</h5>
                </div>
                <div class="modal-body" id="updateForm">
                    {% include 'pages/project/partials/updateForm.html' %}
                </div>
            </div>
        </div>
    </div>
    <!-- {# SECOND MODAL END #} -->

{% endblock %}
{% block script %}
<!-- {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script> #} -->
    <script src="https://unpkg.com/htmx.org@latest/dist/htmx.js"></script>
    <script>
        $('#addProject').on('hidden.bs.modal', function () {
            $(this).find('form').trigger('reset');
        })
    </script>
{% endblock %}


templates/pages/project/projectDetail.html
{% extends 'layout/app.html' %}

{% block title %} Workflow {% endblock %}


{% load static %}
{% load widget_tweaks %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-main">
                    <h4 class="text-capitalize breadcrumb-title">Project - {{ project.project_name }}</h4>
                    <div class="breadcrumb-action justify-content-center flex-wrap">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'project:projects' %}"><i
                                        class="las la-home"></i>Project</a></li>
                                <li class="breadcrumb-item active"
                                    aria-current="page">{{ project.project_name }}
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>    
        {% endfor %}
        <div class="row mt-3">
            <div class="col-12">
                <div class="card card-default card-md mb-4">
                    <div class="card-body">
                        <div class="tab-wrapper">
                            <div class="dm-tab tab-horizontal">
                                <ul class="nav nav-tabs vertical-tabs" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="tab-horizontal-1-tab" data-bs-toggle="tab"
                                           href="#tab-horizontal-1"
                                           role="tab" aria-controls="tab-horizontal-1" aria-selected="true">Datasets</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="tab-horizontal-2-tab" data-bs-toggle="tab"
                                           href="#tab-horizontal-2"
                                           role="tab" aria-controls="tab-horizontal-1"
                                           aria-selected="false">Models</a>
                                    </li>
                                </ul>
                                <div class="tab-content">

                                   {# DATASET #}
                                    <div class="tab-pane fade show active" id="tab-horizontal-1" role="tabpanel"
                                         aria-labelledby="tab-horizontal-1-tab">
                                        <div class="userDatatable userDatatable--ticket userDatatable--ticket--2 mt-1">
                                            <div class="action-btn my-3">
                                                <a class="btn btn-primary shadow" data-bs-toggle="modal" href="#addDataset" role="button" aria-expanded="false"
                                                    aria-controls="collapseOne">Add Dataset</a>
                                            </div>
                                            <!-- <a class="btn btn-primary shadow" href="{% url 'dataset:s3Data' project.id %}">Get data</a> -->
                                            <div>
                                                {% include 'pages/project/dataset/datasetTable.html' %}
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <!-- DATASET MODAL -->
                                    <div class="modal fade" id="addDataset" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                        aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header justify-content-center">
                                                    <h5 class="modal-title" id="exampleModalLabel">Add Dataset</h5>
                                                </div>
                                                <div class="modal-body">
                                                    {% include 'pages/project/dataset/datasetCreateForm.html' %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    {# MODELS #}
                                    <div class="tab-pane fade" id="tab-horizontal-2" role="tabpanel"
                                         aria-labelledby="tab-horizontal-2-tab">
                                        <div class="userDatatable userDatatable--ticket userDatatable--ticket--2 mt-1">
                                            <div class="action-btn my-3">
                                                <a class="btn btn-primary shadow" data-bs-toggle="modal" href="#addModel" role="button"
                                                aria-expanded="false" aria-controls="collapseOne">Add Model</a>
                                            </div>
                                            <div>
                                                {% include 'pages/project/models/modelTable.html' %}
                                            </div>
                                        </div>
                                    </div>

                                    <!-- MODEL SETUP MODAL -->
                                    <div class="modal fade" id="addModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                        aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header justify-content-center">
                                                    <h5 class="modal-title" id="exampleModalLabel">Add Model</h5>
                                                </div>
                                                <div class="modal-body">
                                                      {% include 'pages/project/models/modelCreateForm.html' %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <!-- MODEL CONFIG MODAL -->
                                        <div class="modal fade" id="addModelConfig" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                        aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header justify-content-center">
                                                    <h5 class="modal-title" id="exampleModalLabel">Setup Model Configuration</h5>
                                                </div>
                                                <div class="modal-body">
                                                    {% include 'pages/project/models/modelConfigForm.html' %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block script %}
    <script src="https://unpkg.com/htmx.org@latest/dist/htmx.js"></script>
    <script>
    function getModelId(id) {
        document.getElementById('id_model').value = id;
    }
    </script>
{% endblock script %}
    

