aiEngine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dataset/', include('dataset.urls', namespace='dataset')),
    path('model/', include('modelMarketplace.urls', namespace='model')),
    path('', include('project.urls', namespace='project')),
    path('__debug__/', include('debug_toolbar.urls'))
]

dataset/urls.py
from django.urls import path
from dataset import views

app_name = 'dataset'

urlpatterns = [
    path('<int:pk>/create', views.datasetCreate, name='datasetCreate'),
    path('<int:pk>/delete/<str:data_pk>', views.datasetDelete, name='datasetDelete'),
    path('<int:pk>/getData', views.getStorageData, name='s3Data'),
]

project/urls.py
from django.urls import path
from project import views

app_name = 'project'

urlpatterns = [
    # folder
    # path('api', views.projectView),
    # path('api/<int:pk>', views.projectView),
    # path('api/delete/<int:pid>', views.projectDelete),
    # path('api/update/<int:pid>', views.projectUpdate),

    # views
    path('', views.index, name='index'),
    path('projects', views.projectView, name='projects'),
    path('<int:pk>', views.projectDetailedView, name='project'),
    path('create', views.createProject, name='projectCreate'),
    path('update', views.updateProject, name='projectUpdate'),
    path('instance/<int:pk>', views.projectInstance, name='projectInstance'),
    path('delete/<int:pk>', views.deleteProject, name='projectDelete'),
]

project/models.py
from django.db import models


class Project(models.Model):
    STATUS_CHOICES = (
        ('Complete', 'complete'),
        ('Active', 'active'),
        ('Inactive', 'inactive'),
    )

    project_name = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Active', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.project_name

    class Meta:
        verbose_name_plural = 'Project'

project/forms.py
from django import forms
from project.models import Project


class ProjectForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Project
        fields = '__all__'

project/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from project.models import Project
from project.forms import ProjectForm
from dataset.models import Dataset
from dataset.forms import DatasetForm
from modelMarketplace.models import ModelSetup, ModelTrainingConfig, ModelHistoryDetails
from modelMarketplace.forms import ModelSetupForm, ModelTrainingConfigForm, ModelHistoryDetailsForm

def index(request):
    return render(request, 'dashboard/main.html')


def projectView(request):

    form = ProjectForm()
    data = Project.objects.all()
    context = {"projects": data, "form": form}
    return render(request, 'pages/project/project.html', context)


def projectDetailedView(request, pk):
    project = Project.objects.get(id=pk)
    datasets = Dataset.objects.filter(project=project.id)
    models = ModelSetup.objects.all()
    datasetForm = DatasetForm()
    modelSetupForm = ModelSetupForm()
    modelConfigForm = ModelTrainingConfigForm()
    context = {"project": project,
               "datasets": datasets,
               "datasetForm": datasetForm,
               "models": models,
               "modelForm": modelSetupForm,
               "modelConfigForm": modelConfigForm}
    return render(request, 'pages/project/projectDetail.html', context)


def createProject(request):
    form = ProjectForm(request.POST)
    if form.is_valid():
        form.save()
    else:
        messages.warning(request, "Unable to add project")
    data = Project.objects.all()
    context = {"projects": data}
    return render(request, 'pages/project/partials/table.html', context)


def projectInstance(request, pk):
    """
    When update button is clicked, this function receives a GET request to render
    Update form populated with the instance associated with the id
    :param request:
    :param pk:
    :return: Update Form with instance
    """
    instance = Project.objects.get(id=pk)
    form = ProjectForm(instance=instance)
    context = {"form": form}
    return render(request, 'pages/project/partials/updateForm.html', context)


def updateProject(request):
    project_id = request.POST.get('id')
    instance = Project.objects.get(id=project_id)
    form = ProjectForm(request.POST, instance=instance)
    if form.is_valid():
        form.save()
    else:
        messages.danger(request, "Unable to Update Project")
    data = Project.objects.all()
    context = {"projects": data}
    return render(request, 'pages/project/partials/table.html', context)


@csrf_exempt
def deleteProject(request, pk):
    project = Project.objects.get(id=pk)
    project.delete()
    data = Project.objects.all()
    context = {"projects": data}
    return render(request, 'pages/project/partials/table.html', context)



templates/pages/project/partials/message.html
{% for message in messages %}
<div class="alert alert-{{ message.tags }}" role="alert">
  {{ message }}
</div>
{% endfor %}

templates/pages/project/partials/table.html
<table class="table mb-0 table-borderless">
    <thead>
    <tr class="userDatatable-header">
        <th>
            <span class="userDatatable-title">ID</span>
        </th>
        <th>
            <span class="userDatatable-title">Project</span>
        </th>
        <th>
            <span class="userDatatable-title">Status</span>
        </th>
        <th class="actions">
            <span class="userDatatable-title">Actions</span>
        </th>
    </tr>
    </thead>
    <tbody>
    {% for project in projects %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <div class="d-flex">
                    <div class="userDatatable-inline-title">
                        <a href="{% url 'project:project' project.id %}"
                           class="text-dark fw-500">
                            <h6>{{ project.project_name }}</h6>
                        </a>
                    </div>
                </div>
            </td>
            <td>
                <div class="userDatatable-content d-inline-block">
                    {% if project.status == 'Complete' %}
                        <span class="bg-opacity-success  color-success userDatatable-content-status active">Complete</span>
                    {% elif project.status == 'Active' %}
                        <span class="bg-opacity-primary  color-primary userDatatable-content-status active">Active</span>
                    {% else %}
                        <span class="bg-opacity-danger  color-danger userDatatable-content-status active">Inactive</span>
                    {% endif %}
                </div>
            </td>
            <td>
                <ul class="orderDatatable_actions mb-0 d-flex flex-wrap">
                    <li>
                        <a href="{% url 'project:project' project.id %}" class="view">
                            <i class="fa fa-server"></i>
                        </a>
                    </li>
                    <li>
                        <a data-bs-toggle="modal"
                           href="#updateProject" role="button"
                           aria-expanded="false" aria-controls="collapseOne"
                           class="edit"  hx-get="{% url 'project:projectInstance' project.id %}"
                           hx-trigger="click" hx-target="#updateForm">
                            <i class="uil uil-edit"></i>
                        </a>
                    </li>
                    <li>
                        <a href="" hx-delete="{% url 'project:projectDelete' project.pk %}"
                                hx-confirm="Delete Project ?"
                                hx-target="#projectList"
                                class="remove">
                            <i class="uil uil-trash-alt"></i>
                        </a>
                    </li>
                </ul>
            </td>
        </tr>
    {% endfor %}

    </tbody>
</table>

templates/pages/project/partials/updateForm.html
{% load widget_tweaks %}
<form method="POST">
    {% csrf_token %}
    <div class="mb3">
        {% render_field form.id class="form-control" %}
    </div>
    <div class="mb3">
        <label for="a8" class="il-gray fs-14 fw-500 align-center mb-10">Name of Project</label>
        {% render_field form.project_name class="form-control" %}
    </div>
    <div class="mb3">
        <label for="a8" class="il-gray fs-14 fw-500 align-center mb-10">Status {{ project.status }}</label>
        {% render_field form.status class="form-select" value="{{ project.status }}" %}
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary" hx-post="{% url 'project:projectUpdate' %}" hx-target="#projectList" data-bs-dismiss="modal">Submit</button>
    </div>
</form>