aiEngine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dataset/', include('dataset.urls', namespace='dataset')),
    path('model/', include('modelMarketplace.urls', namespace='model')),
    path('', include('project.urls', namespace='project')),
    path('__debug__/', include('debug_toolbar.urls'))
]

dataset/urls.py
from django.urls import path
from dataset import views

app_name = 'dataset'

urlpatterns = [
    path('<int:pk>/create', views.datasetCreate, name='datasetCreate'),
    path('<int:pk>/delete/<str:data_pk>', views.datasetDelete, name='datasetDelete'),
    path('<int:pk>/getData', views.getStorageData, name='s3Data'),
]

modelMarketplace/urls.py
from django.urls import path
from modelMarketplace import views

app_name = 'model'

urlpatterns = [
    path('<int:pk>/create', views.modelCreate, name='modelCreate'),
    path('<int:pk>/createConfig', views.modelConfig, name='modelConfig'),
    path('<int:pk>/delete/<str:model_pk>', views.modelDelete, name='modelDelete'),
    path('<int:pk>/training/<str:model_pk>', views.modelTraining, name='modelTraining'),
]

project/urls.py
from django.urls import path
from project import views

app_name = 'project'

urlpatterns = [
    # folder
    # path('api', views.projectView),
    # path('api/<int:pk>', views.projectView),
    # path('api/delete/<int:pid>', views.projectDelete),
    # path('api/update/<int:pid>', views.projectUpdate),

    # views
    path('', views.index, name='index'),
    path('projects', views.projectView, name='projects'),
    path('<int:pk>', views.projectDetailedView, name='project'),
    path('create', views.createProject, name='projectCreate'),
    path('update', views.updateProject, name='projectUpdate'),
    path('instance/<int:pk>', views.projectInstance, name='projectInstance'),
    path('delete/<int:pk>', views.deleteProject, name='projectDelete'),
]

dataset/models.py
import uuid
from django.db import models
from project.models import Project
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError


########### File Management System ############

class Folder(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    folder_name = models.CharField(max_length=100, null=True, blank=True)
    folder_path = models.CharField(max_length=1024, null=True, blank=True)
    folders = models.ManyToManyField('self', related_name='subFolders', symmetrical=False, blank=True)  # Many folders -> Many sub-folders
    parents = models.ForeignKey('self', related_name='parentFolders', on_delete=models.CASCADE, null=True, blank=True)  # Many folders -> One parent folder
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.parents:
            return self.parents.folder_name + " " + self.folder_name
        return self.folder_name

def get_upload_path(instance, filename):
    return instance.parent.folder_path + "/" + filename


class File(models.Model):
    file_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    file_name = models.CharField(max_length=256, null=True, blank=True)
    file_path = models.CharField(max_length=1024, blank=True, null=True)
    file_size = models.IntegerField(blank=True, null=True)
    file_extension = models.CharField(max_length=10, blank=True, null=True)
    file_upload = models.FileField(upload_to=get_upload_path)
    parent = models.ForeignKey(Folder, on_delete=models.CASCADE, blank=True, null=True)  # link to parent folder

    def __str__(self):
        return self.file_name

    class Meta:
        abstract = True


############# End of File System ##################


############# Dataset #################

class DatasetBaseModel(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Dataset(DatasetBaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=256)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='projectDataset')
    train_ratio = models.FloatField(default=0.0, validators=[MinValueValidator(0.0), MaxValueValidator(1.0)])
    val_ratio = models.FloatField(default=0.0, validators=[MinValueValidator(0.0), MaxValueValidator(1.0)])
    parent_folder = models.ForeignKey(Folder, on_delete=models.CASCADE, related_name='dataParentFolder', blank=True)

    def __str__(self):
        return f"Raw Dataset: {self.name}"

    def clean(self):
        total = self.train_ratio + self.val_ratio
        if round(total, 2) != 1:
            raise ValidationError("The Sum of ratios should be exactly 1")

    class Meta:
        verbose_name_plural = 'Raw Dataset'


class ProcessedDataset(DatasetBaseModel):
    SUBSET_CHOICES = (
        ('training', 'Training'),
        ('validation', 'Validation'),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=256, null=True, blank=True)
    subset = models.CharField(max_length=20, choices=SUBSET_CHOICES, null=True, blank=True)
    sample_counts = models.IntegerField(default=0)
    raw_dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE, related_name='processedData')

    def __str__(self):
        return f"Processed Dataset: {self.name}"

    class Meta:
        verbose_name_plural = 'Processed Dataset'

class DatasetFile(File):
    processed_dataset = models.ForeignKey(ProcessedDataset, on_delete=models.CASCADE, related_name='datasetFile', blank=True)

    def __str__(self):
        return f"Dataset File: {self.file_name}"

    class Meta:
        verbose_name_plural = 'Dataset File'

# class Annotation(DatasetBaseModel):
#     FORMAT_CHOICES = (
#         ('COCO', 'coco'),
#         ('Pascal VOC', 'pascalVoc'),
#         ('YOLO', 'yolo')
#     )
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#     name = models.CharField(max_length=256, null=True, blank=True)
#     processed_dataset = models.ForeignKey(ProcessedDataset, on_delete=models.CASCADE, related_name='annotations',
#                                           null=True, blank=True, default=None)
#     format = models.CharField(max_length=20, choices=FORMAT_CHOICES)
#     count = models.IntegerField(default=0)

#     def __str__(self):
#         return f"Annotation: {self.name}"

#     class Meta:
#         verbose_name_plural = 'Annotation'


class AnnotationFile(File):
    processed_dataset = models.ForeignKey(ProcessedDataset, on_delete=models.CASCADE, related_name='annotationFile')

    def __str__(self):
        return f"Annotation File: {self.file_name}"

    class Meta:
        verbose_name_plural = 'Annotation File'


class ConfigFile(File):
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE, related_name="datasetConfigFile")

    def __str__(self):
        return f"Config File: {self.file_name}"

    class Meta:
        verbose_name_plural = 'Configuration File'


modelMarketplace/models.py
import uuid
from django.db import models
from project.models import Project
from dataset.models import ProcessedDataset

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class ModelSetup(BaseModel):
    MODEL_CHOICES = (
        ('classification', 'Classification'),
        ('detection', 'Object Detection'),
        ('segmentation', 'Image Segmentation')
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=256)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='projectModel', blank=True)
    model_type = models.CharField(max_length=20, choices=MODEL_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Model Setup"


class ModelTrainingConfig(BaseModel):

    # CHOICES = (( WHAT GOES TO DB, WHAT USER SEES ))
    IMAGE_SIZE_CHOICES = (
        (224, "224x224"),
        (256, "256x256"),
        (416, "416x416"),
        (512, "512x512"),
        (640, "640x640"),
        (1024, "1024x1024"),
    )
    MODEL_CHOICE = (
        ("yolov5n", "YOLOv5 Nano"),
        ("yolov5s", "YOLOv5 Small"),
        ("yolov5m", "YOLOv5 Medium"),
        ("yolov5l", "YOLOv5 Large"),
        ("yolov5x", "YOLOv5 Extra-Large"),
    )
    BATCH_SIZE_CHOICE = (
        (16, 16),
        (32, 32),
        (64, 64),
        (128, 128),
    )
    OPTIMIZER_CHOICE = (
        ("SGD", "Stochastic Gradient Descent (SGD)"),
        ("Adam", "ADAM"),
        ("AdamW", "ADAM (Weight Decay)"),
    )
    model = models.ForeignKey(ModelSetup, on_delete=models.CASCADE, related_name='modelTraining')
    num_of_epochs = models.PositiveIntegerField(null=True, blank=True)
    img_size = models.PositiveIntegerField(choices=IMAGE_SIZE_CHOICES, default=640, null=True, blank=True)
    batch_size = models.PositiveIntegerField(choices=BATCH_SIZE_CHOICE, default=32, null=True, blank=True)
    yolo_choice = models.CharField(max_length=50, choices=MODEL_CHOICE, default="yolov5s", null=True, blank=True)
    optimizer = models.CharField(max_length=50, choices=OPTIMIZER_CHOICE, default="SGD", null=True, blank=True)

    def __str__(self):
        return "Training " + self.model.name

    class Meta:
        verbose_name_plural = "Model Training Config"


class ModelHistoryDetails(BaseModel):
    model = models.ForeignKey(ModelSetup, on_delete=models.CASCADE, related_name='modelHistory')
    train_accuracy = models.JSONField(null=True, blank=True)
    val_accuracy = models.JSONField(null=True, blank=True)
    train_loss = models.JSONField(null=True, blank=True)
    val_loss = models.JSONField(null=True, blank=True)
    classification_report = models.JSONField(null=True, blank=True)

    def __str__(self):
        return "History " + self.model.name

    class Meta:
        verbose_name_plural = "Model History Details"

project/models.py
from django.db import models


class Project(models.Model):
    STATUS_CHOICES = (
        ('Complete', 'complete'),
        ('Active', 'active'),
        ('Inactive', 'inactive'),
    )

    project_name = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Active', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.project_name

    class Meta:
        verbose_name_plural = 'Project'

project/forms.py
from django import forms
from project.models import Project


class ProjectForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Project
        fields = '__all__'

project/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from project.models import Project
from project.forms import ProjectForm
from dataset.models import Dataset
from dataset.forms import DatasetForm
from modelMarketplace.models import ModelSetup, ModelTrainingConfig, ModelHistoryDetails
from modelMarketplace.forms import ModelSetupForm, ModelTrainingConfigForm, ModelHistoryDetailsForm

def index(request):
    return render(request, 'dashboard/main.html')


def projectView(request):

    form = ProjectForm()
    data = Project.objects.all()
    context = {"projects": data, "form": form}
    return render(request, 'pages/project/project.html', context)


def projectDetailedView(request, pk):
    project = Project.objects.get(id=pk)
    datasets = Dataset.objects.filter(project=project.id)
    models = ModelSetup.objects.all()
    datasetForm = DatasetForm()
    modelSetupForm = ModelSetupForm()
    modelConfigForm = ModelTrainingConfigForm()
    context = {"project": project,
               "datasets": datasets,
               "datasetForm": datasetForm,
               "models": models,
               "modelForm": modelSetupForm,
               "modelConfigForm": modelConfigForm}
    return render(request, 'pages/project/projectDetail.html', context)


def createProject(request):
    form = ProjectForm(request.POST)
    if form.is_valid():
        form.save()
    else:
        messages.warning(request, "Unable to add project")
    data = Project.objects.all()
    context = {"projects": data}
    return render(request, 'pages/project/partials/table.html', context)


def projectInstance(request, pk):
    """
    When update button is clicked, this function receives a GET request to render
    Update form populated with the instance associated with the id
    :param request:
    :param pk:
    :return: Update Form with instance
    """
    instance = Project.objects.get(id=pk)
    form = ProjectForm(instance=instance)
    context = {"form": form}
    return render(request, 'pages/project/partials/updateForm.html', context)


def updateProject(request):
    project_id = request.POST.get('id')
    instance = Project.objects.get(id=project_id)
    form = ProjectForm(request.POST, instance=instance)
    if form.is_valid():
        form.save()
    else:
        messages.danger(request, "Unable to Update Project")
    data = Project.objects.all()
    context = {"projects": data}
    return render(request, 'pages/project/partials/table.html', context)


@csrf_exempt
def deleteProject(request, pk):
    project = Project.objects.get(id=pk)
    project.delete()
    data = Project.objects.all()
    context = {"projects": data}
    return render(request, 'pages/project/partials/table.html', context)



templates/pages/project/models/modelConfigForm.html
{% load widget_tweaks %}
<form method="POST" enctype="multipart/form-data" hx-encoding="multipart/form-data">
    {% csrf_token %}

    <input type="text" class="form-control" id="id_model" name="model" hidden>
    <div class="row">
        <div class="form-group">
            <label for="a8" class="il-gray fs-14 fw-500 align-center mb-10">Number of Epochs</label>
            {% render_field modelConfigForm.num_of_epochs class="form-control" %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label for="a8" class="il-gray fs-14 fw-500 align-center mb-10">Image Size</label>
                {% render_field modelConfigForm.img_size class="form-select" %}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="a8" class="il-gray fs-14 fw-500 align-center mb-10">Batch Size</label>
                {% render_field modelConfigForm.batch_size class="form-select" %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label for="a8" class="il-gray fs-14 fw-500 align-center mb-10">Optimizer</label>
                {% render_field modelConfigForm.optimizer class="form-select" %}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="a8" class="il-gray fs-14 fw-500 align-center mb-10">Model Size</label>
                {% render_field modelConfigForm.yolo_choice class="form-select" %}
            </div>
        </div>
    </div>
    

    <div class="row d-flex justify-content-end">
        <button type="submit" class="btn btn-primary" hx-post="{% url 'model:modelConfig' project.id  %}"
             data-bs-dismiss="modal">Submit</button>
    </div>
</form>

templates/pages/project/models/modelCreateForm.html
{% load widget_tweaks %}
<form method="POST" enctype="multipart/form-data" hx-encoding="multipart/form-data">
    {% csrf_token %}

    <input type="text" class="form-control" id="id_project" name="project" value="{{ project.id }}" hidden>
    <div class="row">
        <div class="form-group">
            <label for="a8" class="il-gray fs-14 fw-500 align-center mb-10">Name of Model</label>
            {% render_field modelForm.name class="form-control" %}
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <label for="a8" class="il-gray fs-14 fw-500 align-center mb-10">Type of Model</label>
            {% render_field modelForm.model_type class="form-select" %}
        </div>
    </div>
    <br>

    <div class="row d-flex justify-content-end">
        <button type="submit" class="btn btn-primary" hx-post="{% url 'model:modelCreate' project.id  %}"
            hx-target="#modelList" data-bs-dismiss="modal">Submit</button>
    </div>
</form>

templates/pages/project/models/modelTable.html
<div class="table-responsive" id="modelList">
    <table class="table mb-0 table-borderless">
        <thead>
        <tr class="userDatatable-header">
            <th>
                <span class="userDatatable-title">ID</span>
            </th>
            <th>
                <span class="userDatatable-title">Name</span>
            </th>
            <th>
                <span class="userDatatable-title">Type</span>
            </th>
            <th class="actions">
                <span class="userDatatable-title">Actions</span>
            </th>
        </tr>
        </thead>
        <tbody>
        {% for model in models %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <div class="d-flex">
                        <div class="userDatatable-inline-title">
                            <a href="#" class="text-dark fw-500">
                                <h6>{{ model.name }}</h6>
                            </a>
                        </div>
                    </div>
                </td>
                <td>
                    <div class="d-flex">
                        <div class="userDatatable-inline-title">
                            <h6>{{ model.model_type }}</h6>
                        </div>
                    </div>
                </td>
                <td>
                    <ul class="orderDatatable_actions mb-0 d-flex flex-wrap">
                        <li>
                            <a class="view" data-bs-toggle="modal" href="#addModelConfig" onclick="getModelId(`{{ model.id }}`)"
                            aria-expanded="false" aria-controls="collapseOne">
                                <i class="fa fa-plus"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'model:modelTraining' pk=project.id model_pk=model.id %}" class="edit">
                                <i class="fa fa-server"></i>
                            </a>
                        </li>
                        <li>
                            <a href="" hx-delete="{% url 'model:modelDelete' pk=project.id model_pk=model.id %}"
                               hx-confirm="Delete Model ?"
                               hx-target="#modelList"
                               class="remove">
                                <i class="uil uil-trash-alt"></i>
                            </a>
                        </li>
                    </ul>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
</div>